version: '3.5'

services:
  gui:
    image: andrius/gui
    shm_size: '1gb'
    environment:
      - LOGIN_PASSWORD=p@sSw0rd

  novnc:
    image: andrius/novnc
    environment:
      - VNC_SERVER=gui
      - VNC_PORT=5900
      - LISTEN_INTERFACE=0.0.0.0
      - LISTEN_PORT=18080
    ports:
      - 0.0.0.0:18080:18080
